# ---- Build Stage ----
FROM docker.io/golang:1.24 AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o main .

# ---- Run Stage ----
FROM registry.access.redhat.com/ubi8/ubi-minimal

RUN microdnf install shadow-utils

WORKDIR /app


COPY --from=builder /app/main .

RUN useradd -u 1001 -g 0 -M -s /sbin/nologin appuser && \
    chown -R 1001:0 /app && \
    chmod -R g=u /app && \
    chmod g=u /etc/passwd

USER 1001

EXPOSE 8080

ENTRYPOINT ["/app/main"]

